// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	//tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	zToolkitSidebar: [
	{
		type: 'category',
		label: 'ZToolkit',
		items: [
		'zToolkit/intro',   
		'zToolkit/dynamo',    
		'zToolkit/grasshopper', 
		],
	}],
	zToolsSidebar: [
	{
		type: 'category',
		label: 'ZTools Revit',
		items: [
		'zToolsRevit/intro',     
		'zToolsRevit/style-manager',    
		'zToolsRevit/section-export',   
		'zToolsRevit/view-sheet-manager',  
		],
	},
	{
		type: 'category',
		label: 'ZTools Navisworks',
		items: [
		'zToolsNavisworks/intro',     
		'zToolsNavisworks/clash-data-reporting',    
		],
	}],
	zToolsContributionSidebar: [
	{
		type: 'category',
		label: 'ZTools Revit Contribution',
		items: [
		'contribution/zTools/intro',   
		'contribution/zTools/github',   
		'contribution/zTools/visualStudio',  
		],
	},
	{
		type: 'category',
		label: 'ZToolkit Contribution',
		items: [
		'contribution/zToolkit/intro',   
		'contribution/zToolkit/github',   
		'contribution/zToolkit/visualStudio',  
		],
	},
	{
		type: 'category',
		label: 'Wiki',
		items: [
		'contribution/wiki/intro',   
		],
	},
	],
	zTechTemplatesSidebar: [{type: 'autogenerated', dirName: 'zTechTemplates'}],

	// But you can create a sidebar manually
	/*
	tutorialSidebar: [
		'intro',
		'hello',
		{
		type: 'category',
		label: 'Tutorial',
		items: ['tutorial-basics/create-a-document'],
		},
	],
	*/
};

export default sidebars;
